// Generated by CoffeeScript 1.7.1
var CityModel, extend, u,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

u = ABM.util;

extend = function(obj, mixin) {
  var method, name;
  for (name in mixin) {
    method = mixin[name];
    obj[name] = method;
  }
  return obj;
};

CityModel = (function(_super) {
  var _ref;

  __extends(CityModel, _super);

  function CityModel() {
    return CityModel.__super__.constructor.apply(this, arguments);
  }

  CityModel.log = function(msg) {};

  if ((_ref = CityModel.instance) != null ? _ref.debugging : void 0) {
    console.log(msg);
  }

  CityModel.instance = null;

  CityModel.get_patch_at = function(point) {
    return this.instance.patches.patchXY(Math.round(point.x), Math.round(point.y));
  };

  CityModel.is_on_world = function(point) {
    return this.instance.patches.isOnWorld(Math.round(point.x), Math.round(point.y));
  };

  CityModel.link_agents = function(agent_a, agent_b) {
    return this.instance.links.create(agent_a, agent_b);
  };

  CityModel.prototype.setup = function() {
    CityModel.instance = this;
    this.set_up_AStar_helpers();
    this.set_default_params();
    this.initialize_modules();
    this.init_patches();
    return this.spawn_entities();
  };

  CityModel.prototype.step = function() {
    var agent, _i, _len, _ref1, _results;
    _ref1 = this.agents;
    _results = [];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      agent = _ref1[_i];
      _results.push(agent.step());
    }
    return _results;
  };

  CityModel.prototype.draw = function() {
    switch (this.draw_mode) {
      case "normal":
        this.draw_normal_color();
        break;
      case "connectivity":
        this.draw_connectivity_color();
    }
    return CityModel.__super__.draw.apply(this, arguments);
  };

  CityModel.prototype.initialize_modules = function() {
    Road.initialize_module(this.roads);
    RoadNode.initialize_module(this.road_nodes);
    RoadMaker.initialize_module(this.road_makers);
    HouseMaker.initialize_module(this.house_makers);
    Inspector.initialize_module(this.inspectors);
    return Planner.initialize_module(this.planners);
  };

  CityModel.prototype.create_city_hall = function(x, y) {
    var patch;
    patch = this.patches.patchXY(x, y);
    patch.color = patch.default_color = [0, 0, 100];
    patch.dist_to_city_hall = 0;
    return patch;
  };

  CityModel.prototype.set_default_params = function() {
    this.patchBreeds("roads houses");
    this.agentBreeds("road_makers house_makers road_nodes inspectors planners");
    this.anim.setRate(120, false);
    this.refreshPatches = true;
    return this.draw_mode = "normal";
  };

  CityModel.prototype.spawn_entities = function() {
    var patch, _i, _j, _len, _len1, _ref1, _ref2;
    this.city_hall = this.create_city_hall(0, 0);
    _ref1 = this.city_hall.n4;
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      patch = _ref1[_i];
      Road.set_breed(patch, 1);
    }
    _ref2 = this.city_hall.n;
    for (_j = 0, _len1 = _ref2.length; _j < _len1; _j++) {
      patch = _ref2[_j];
      if (!(patch.breed === this.roads)) {
        Road.set_breed(patch, 2);
      }
    }
    this.spawn_road_makers(1);
    this.spawn_house_makers(0);
    this.spawn_inspectors(1);
    return Planner.spawn_planner();
  };

  CityModel.prototype.spawn_road_makers = function(ammount) {
    var i, patch, _results;
    i = 0;
    _results = [];
    while (i < ammount) {
      patch = u.oneOf(this.city_hall.n4);
      RoadMaker.spawn_road_maker(patch);
      _results.push(i += 1);
    }
    return _results;
  };

  CityModel.prototype.spawn_house_makers = function(ammount) {
    var i, patch, _results;
    i = 0;
    _results = [];
    while (i < ammount) {
      patch = u.oneOf(this.city_hall.n4);
      HouseMaker.spawn_house_maker(patch);
      _results.push(i += 1);
    }
    return _results;
  };

  CityModel.prototype.spawn_inspectors = function(ammount) {
    var i, patch, _results;
    i = 0;
    _results = [];
    while (i < ammount) {
      patch = u.oneOf(this.city_hall.n4);
      Inspector.spawn_inspector(patch);
      _results.push(i += 1);
    }
    return _results;
  };

  CityModel.prototype.set_up_AStar_helpers = function() {
    var height, width, x_to_grid_transform, x_to_world_transform, y_to_grid_transform, y_to_world_transform;
    width = this.world.maxX - this.world.minX;
    height = this.world.maxY - this.world.minY;
    x_to_grid_transform = (function(_this) {
      return function(x) {
        return x - _this.world.minX;
      };
    })(this);
    y_to_grid_transform = (function(_this) {
      return function(y) {
        return -y - _this.world.minY;
      };
    })(this);
    x_to_world_transform = (function(_this) {
      return function(x) {
        return x + _this.world.minX;
      };
    })(this);
    y_to_world_transform = (function(_this) {
      return function(y) {
        return -(y + _this.world.minY);
      };
    })(this);
    this.roadAStar = new AStarHelper(width, height, false);
    this.roadAStar.setToGridTransforms(x_to_grid_transform, y_to_grid_transform);
    this.roadAStar.setToWorldTransforms(x_to_world_transform, y_to_world_transform);
    this.terrainAStar = new AStarHelper(width, height, true);
    this.terrainAStar.setToGridTransforms(x_to_grid_transform, y_to_grid_transform);
    return this.terrainAStar.setToWorldTransforms(x_to_world_transform, y_to_world_transform);
  };

  CityModel.prototype.init_patches = function() {
    var b, g, p, r, _i, _len, _ref1, _ref2, _results;
    _ref1 = this.patches;
    _results = [];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      p = _ref1[_i];
      p.color = u.randomGray(100, 150);
      _ref2 = p.color, r = _ref2[0], g = _ref2[1], b = _ref2[2];
      p.color = [r, g * 2, b];
      _results.push(p.default_color = p.color);
    }
    return _results;
  };

  CityModel.prototype.draw_mode = function(mode) {
    return this.draw_mode = mode;
  };

  CityModel.prototype.draw_normal_color = function() {
    var patch, _i, _len, _ref1, _results;
    _ref1 = this.patches;
    _results = [];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      patch = _ref1[_i];
      if (patch.breed.name === "patches") {
        _results.push(patch.color = patch.default_color);
      }
    }
    return _results;
  };

  CityModel.prototype.draw_connectivity_color = function() {
    var patch, _i, _len, _ref1, _results;
    _ref1 = this.patches;
    _results = [];
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      patch = _ref1[_i];
      if (patch.breed.name === "patches") {
        _results.push(patch.color = patch.connectivity_color != null ? patch.connectivity_color : patch.color);
      }
    }
    return _results;
  };

  return CityModel;

})(ABM.Model);
