// Generated by CoffeeScript 1.7.1
var BaseAgent;

BaseAgent = (function() {
  function BaseAgent() {}

  BaseAgent.prototype.current_state = null;

  BaseAgent.prototype.init = function() {};

  BaseAgent.prototype.step = function() {
    return this.current_state();
  };

  BaseAgent.prototype._set_state = function(new_state) {
    this._log("" + this.id + ": " + this.label + " -> " + new_state);
    this.label = this._get_label(new_state);
    return this.current_state = this['s_' + new_state];
  };

  BaseAgent.prototype._set_initial_state = function(state) {
    this._log("" + this.id + ": @" + state);
    this.label = this._get_label(state);
    return this.current_state = this['s_' + state];
  };

  BaseAgent.prototype._get_label = function(state) {
    var label;
    if (this.show_ids) {
      label = "" + this.id;
    }
    if (this.show_ids && this.show_states) {
      label += ": ";
    }
    if (this.show_states) {
      label += "" + state;
    }
    return label;
  };

  BaseAgent.prototype._log = function(msg) {
    if (this.show_logs) {
      return console.log(msg);
    }
  };

  BaseAgent.prototype._move = function(point) {
    this._face_point(point);
    return this.forward(this.speed);
  };

  BaseAgent.prototype._face_point = function(point) {
    var heading, turn;
    heading = this._angle_between_points(point, this);
    turn = ABM.util.subtractRads(heading, this.heading);
    return this.rotate(turn);
  };

  BaseAgent.prototype._angle_between_points = function(point_a, point_b) {
    var dx, dy;
    dx = point_a.x - point_b.x;
    dy = point_a.y - point_b.y;
    return Math.atan2(dy, dx);
  };

  BaseAgent.prototype._in_point = function(point) {
    return 0.1 > ABM.util.distance(this.x, this.y, point.x, point.y);
  };

  BaseAgent.prototype._get_terrain_path_to = function(point) {
    return CityModel.instance.terrainAStar.getPath(this, point);
  };

  BaseAgent.prototype._get_road_path_to = function(point) {
    return CityModel.instance.roadAStar.getPath(this, point);
  };

  return BaseAgent;

})();
