// Generated by CoffeeScript 1.7.1
var BaseAgent;

BaseAgent = (function() {
  function BaseAgent() {}

  BaseAgent.prototype.current_state = null;

  BaseAgent.prototype.current_state_name = null;

  BaseAgent.prototype.init = function() {};

  BaseAgent.prototype.step = function() {
    return this.current_state();
  };

  BaseAgent.prototype._set_state = function(new_state) {
    this._log("" + this.id + ": " + this.current_state_name + " -> " + new_state);
    return this._update_state(new_state);
  };

  BaseAgent.prototype._set_initial_state = function(state) {
    this._log("" + this.id + ": @" + state);
    return this._update_state(state);
  };

  BaseAgent.prototype._update_state = function(state) {
    this.current_state_name = state;
    this.label = this._get_label();
    return this.current_state = this['s_' + this.current_state_name];
  };

  BaseAgent.prototype.update_label = function() {
    return this.label = this._get_label();
  };

  BaseAgent.prototype._get_label = function() {
    var label;
    label = "";
    if (this.show_ids) {
      label = "" + this.id;
    }
    if (this.show_ids && this.show_states) {
      label += ": ";
    }
    if (this.show_states) {
      label += "" + this.current_state_name;
    }
    return label;
  };

  BaseAgent.prototype._log = function(msg) {
    if (this.show_logs) {
      return console.log(msg);
    }
  };

  BaseAgent.prototype._link_to = function(agent) {
    if (this.show_links) {
      return CityModel.link_agents(this, agent);
    }
  };

  BaseAgent.prototype._clear_links = function() {
    var link, _i, _len, _ref, _results;
    _ref = this.myLinks();
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      link = _ref[_i];
      _results.push(link.die());
    }
    return _results;
  };

  BaseAgent.prototype._move = function(point) {
    this._face_point(point);
    return this.forward(this.speed);
  };

  BaseAgent.prototype._face_point = function(point) {
    var heading, turn;
    heading = this._angle_between_points(point, this);
    turn = ABM.util.subtractRads(heading, this.heading);
    return this.rotate(turn);
  };

  BaseAgent.prototype._angle_between_points = function(point_a, point_b) {
    var dx, dy;
    dx = point_a.x - point_b.x;
    dy = point_a.y - point_b.y;
    return Math.atan2(dy, dx);
  };

  BaseAgent.prototype._in_point = function(point) {
    return 0.1 > ABM.util.distance(this.x, this.y, point.x, point.y);
  };

  BaseAgent.prototype._get_terrain_path_to = function(point) {
    return CityModel.instance.terrainAStar.getPath(this, point);
  };

  BaseAgent.prototype._get_road_path_to = function(point) {
    return CityModel.instance.roadAStar.getPath(this, point);
  };

  return BaseAgent;

})();
