// Generated by CoffeeScript 1.7.1
var Inspector, Inspector_instance_properties;

Inspector = (function() {
  function Inspector() {}

  Inspector.inspectors = null;

  Inspector.default_color = [0, 0, 255];

  Inspector.radius_increment = 3;

  Inspector.initialize_module = function(inspectors_breed) {
    this.inspectors = inspectors_breed;
    return this.inspectors.setDefault('color', this.default_color);
  };

  Inspector.spawn_inspector = function(patch) {
    var inspector;
    inspector = patch.sprout(1, this.inspectors)[0];
    extend(inspector, Inspector_instance_properties);
    inspector.init();
    return inspector;
  };

  return Inspector;

})();

Inspector_instance_properties = {
  current_message: null,
  current_state: null,
  init: function() {
    return this.current_state = this.get_message_state;
  },
  step: function() {
    return this.current_state();
  },
  get_message_state: function() {
    this.current_message = Planner.get_message('inspect_endpoint');
    if (this.current_message != null) {
      this.path = CityModel.instance.roadAStar.getPath(this, this.current_message.patch);
      return this.current_state = this.go_to_endpoint_state;
    }
  },
  go_to_endpoint_state: function() {
    this.move(this.path[0]);
    if (this.in_point(this.path[0])) {
      this.path.shift();
      if (this.path.length === 0) {
        return this.current_state = this.inspect_endpoint_state;
      }
    }
  },
  inspect_endpoint_state: function() {
    console.log("Inspecting " + this.current_message.patch);
    this.current_message = null;
    return this.current_state = this.get_message_state;
  },
  move: function(point) {
    this.face_point(point);
    return this.forward(0.05);
  },
  face_point: function(point) {
    var dx, dy, heading, turn;
    dx = point.x - this.x;
    dy = point.y - this.y;
    heading = Math.atan2(dy, dx);
    turn = ABM.util.subtractRads(heading, this.heading);
    return this.rotate(turn);
  },
  in_point: function(point) {
    return 0.1 > ABM.util.distance(this.x, this.y, point.x, point.y);
  }
};
