// Generated by CoffeeScript 1.7.1
var KMeans;

KMeans = (function() {
  KMeans.max_iters = 100;

  KMeans._copy_point = function(point) {
    return {
      x: point.x,
      y: point.y
    };
  };

  KMeans._init_clusters = function(points, number_of_clusters) {
    var clusters, i, index, _i;
    clusters = [];
    for (i = _i = 0; 0 <= number_of_clusters ? _i < number_of_clusters : _i > number_of_clusters; i = 0 <= number_of_clusters ? ++_i : --_i) {
      index = ABM.util.randomInt(points.length);
      clusters.push({
        center: KMeans._copy_point(points[index]),
        points: []
      });
    }
    return clusters;
  };

  KMeans._dist = function(point_a, point_b) {
    return ABM.util.distance(point_a.x, point_a.y, point_b.x, point_b.y);
  };

  KMeans._closest_centroid = function(distances) {
    return ABM.util.minOneOf(distances, function(point) {
      return point.distance;
    }).cluster;
  };

  KMeans._points_are_equal = function(point_a, point_b) {
    return this._dist(point_a, point_b) < 0.1;
  };

  function KMeans(points, number_of_clusters) {
    this.points = points;
    this.number_of_clusters = number_of_clusters;
    this.clusters = KMeans._init_clusters(this.points, this.number_of_clusters);
    this.converged = false;
  }

  KMeans.prototype.run = function() {
    var iters, _results;
    iters = 0;
    _results = [];
    while (!this.converged && iters < KMeans.max_iters) {
      this.step();
      _results.push(iters += 1);
    }
    return _results;
  };

  KMeans.prototype.step = function() {
    this.assign_centroids();
    return this.converged = this.move_centroids();
  };

  KMeans.prototype.assign_centroids = function() {
    var cluster, distances, point, _i, _j, _len, _len1, _ref, _ref1, _results;
    _ref = this.clusters;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      cluster = _ref[_i];
      cluster.points = [];
    }
    _ref1 = this.points;
    _results = [];
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      point = _ref1[_j];
      distances = (function() {
        var _k, _len2, _ref2, _results1;
        _ref2 = this.clusters;
        _results1 = [];
        for (_k = 0, _len2 = _ref2.length; _k < _len2; _k++) {
          cluster = _ref2[_k];
          _results1.push({
            distance: KMeans._dist(point, cluster.center),
            cluster: cluster
          });
        }
        return _results1;
      }).call(this);
      _results.push(KMeans._closest_centroid(distances).points.push(point));
    }
    return _results;
  };

  KMeans.prototype.move_centroids = function() {
    var cluster, mean_position, moved, point, _i, _j, _len, _len1, _ref, _ref1;
    moved = false;
    _ref = this.clusters;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      cluster = _ref[_i];
      mean_position = {
        x: 0,
        y: 0
      };
      _ref1 = cluster.points;
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        point = _ref1[_j];
        mean_position.x += point.x;
        mean_position.y += point.y;
      }
      mean_position.x /= cluster.points.length;
      mean_position.y /= cluster.points.length;
      moved = moved || !KMeans._points_are_equal(cluster.center, mean_position);
      cluster.center = mean_position;
    }
    return moved;
  };

  KMeans.prototype.centroids = function() {
    var cluster;
    return (function() {
      var _i, _len, _ref, _results;
      _ref = this.clusters;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        cluster = _ref[_i];
        _results.push(cluster.center);
      }
      return _results;
    }).call(this);
  };

  return KMeans;

})();
