// Generated by CoffeeScript 1.7.1
var MessageBoard;

MessageBoard = (function() {
  MessageBoard.message_queues = {};

  MessageBoard.initialize = function() {
    return this.message_queues = {};
  };

  MessageBoard._get_or_create_queue = function(type) {
    if (this.message_queues[type] == null) {
      this.message_queues[type] = [];
    }
    return this.message_queues[type];
  };

  MessageBoard.get_board = function(topic) {
    return new MessageBoard(topic);
  };

  function MessageBoard(topic) {
    this.topic = topic;
    this.queue = this.constructor._get_or_create_queue(topic);
  }

  MessageBoard.prototype.get_message = function() {
    return this.queue.shift();
  };

  MessageBoard.prototype.post_message = function(message) {
    if (message == null) {
      message = {};
    }
    message.type = this.topic;
    message.timestamp = Date.now();
    return this.queue.push(message);
  };

  return MessageBoard;

})();

CityModel.register_module(MessageBoard, [], []);
