// Generated by CoffeeScript 1.7.1
var Planner, Planner_instance_properties;

Planner = (function() {
  function Planner() {}

  Planner.planners = null;

  Planner.message_queues = {};

  Planner.initialize_module = function(planners_breed) {
    this.planners = planners_breed;
    this.planners.setDefault('hidden', true);
    return this.message_queues = {};
  };

  Planner.get_message = function(type) {
    var _ref;
    return (_ref = this.message_queues[type]) != null ? _ref.shift() : void 0;
  };

  Planner.post_message = function(type, message) {
    var queue;
    queue = this._get_or_create_queue(type);
    return queue.push(message);
  };

  Planner._get_or_create_queue = function(type) {
    if (this.message_queues[type] == null) {
      this.message_queues[type] = [];
    }
    return this.message_queues[type];
  };

  Planner.spawn_planner = function() {
    var planner;
    planner = this.planners.create(1)[0];
    extend(planner, Planner_instance_properties);
    planner.init();
    return planner;
  };

  return Planner;

})();

Planner_instance_properties = {
  init: function() {},
  step: function() {
    var msg;
    msg = Planner.get_message('connect_nodes');
    if (msg != null) {
      return RoadMaker.spawn_road_maker(msg.node_a.p);
    }
  }
};
