// Generated by CoffeeScript 1.7.1
var Planner, RoadPlanner;

Planner = (function() {
  function Planner() {}

  Planner.planners = null;

  Planner.initialize_module = function(planners_breed) {
    this.planners = planners_breed;
    return this.planners.setDefault('hidden', true);
  };

  Planner.spawn_planner = function() {
    var planner;
    planner = this.planners.create(1)[0];
    extend(planner, Planner.prototype);
    planner.init();
    return planner;
  };

  Planner.prototype.init = function() {
    return this.msg_reader = MessageBoard.get_reader('connect_nodes');
  };

  Planner.prototype.step = function() {
    var msg;
    msg = this.msg_reader.get_message();
    if (msg != null) {
      return RoadMaker.spawn_road_maker(msg.node_a.p);
    }
  };

  return Planner;

})();

RoadPlanner = (function() {
  function RoadPlanner() {}

  RoadPlanner.road_planners = null;

  RoadPlanner.initialize_module = function(road_planners_breed) {
    this.road_planners = road_planners_breed;
    return this.road_planners.setDefault('hidden', true);
  };

  RoadPlanner.spawn_road_planner = function() {
    var road_planner;
    road_planner = this.road_planners.create(1)[0];
    extend(road_planner, RoadPlanner.prototype);
    road_planner.init();
    return road_planner;
  };

  RoadPlanner.prototype.init = function() {
    return this.msg_reader = MessageBoard.get_reader('build_road');
  };

  RoadPlanner.prototype.step = function() {
    var msg;
    msg = this.msg_reader.get_message();
    if (msg != null) {
      return RoadMaker.spawn_road_maker(msg.node_a.p);
    }
  };

  return RoadPlanner;

})();
