// Generated by CoffeeScript 1.7.1
var Planner;

Planner = (function() {
  function Planner() {}

  Planner.message_queues = {};

  Planner.get_message = function(type) {
    var _ref;
    return (_ref = this.message_queues[type]) != null ? _ref.shift() : void 0;
  };

  Planner.post_message = function(type, message) {
    var queue;
    queue = this._get_or_create_queue(type);
    return queue.push(message);
  };

  Planner._get_or_create_queue = function(type) {
    if (this.message_queues[type] == null) {
      this.message_queues[type] = [];
    }
    return this.message_queues[type];
  };

  return Planner;

})();
