// Generated by CoffeeScript 1.7.1
var GrowthPlanner, HousingPlanner, NodeInterconnectivityPlanner, Planner, PlotKeeperPlanner, PlotPlanner, RoadPlanner,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Planner = (function() {
  function Planner() {}

  Planner.planners = null;

  Planner.initialize = function(planners) {
    this.planners = planners;
    this.planners.setDefault('hidden', true);
    return PlotKeeperPlanner.available_plots = [];
  };

  Planner.spawn_road_planner = function() {
    return this.spawn_planner(RoadPlanner);
  };

  Planner.spawn_node_planner = function() {
    return this.spawn_planner(NodeInterconnectivityPlanner);
  };

  Planner.spawn_growth_planner = function() {
    return this.spawn_planner(GrowthPlanner);
  };

  Planner.spawn_plot_planner = function() {
    return this.spawn_planner(PlotPlanner);
  };

  Planner.spawn_housing_planner = function() {
    return this.spawn_planner(HousingPlanner);
  };

  Planner.spawn_plot_keeper_planner = function() {
    return this.spawn_planner(PlotKeeperPlanner);
  };

  Planner.spawn_planner = function(klass) {
    var planner;
    planner = this.planners.create(1)[0];
    extend(planner, FSMAgent, klass);
    planner.init();
    return planner;
  };

  return Planner;

})();

NodeInterconnectivityPlanner = (function(_super) {
  __extends(NodeInterconnectivityPlanner, _super);

  function NodeInterconnectivityPlanner() {
    return NodeInterconnectivityPlanner.__super__.constructor.apply(this, arguments);
  }

  NodeInterconnectivityPlanner.prototype.init = function() {
    this.msg_reader = MessageBoard.get_board('nodes_unconnected');
    return this._set_initial_state('get_message');
  };

  NodeInterconnectivityPlanner.prototype.s_get_message = function() {
    this.message = this.msg_reader.get_message();
    if (this.message != null) {
      return this._set_state('emit_road_connector');
    }
  };

  NodeInterconnectivityPlanner.prototype.s_emit_road_connector = function() {
    if (this.message == null) {
      this._set_state('get_message');
      return;
    }
    RoadBuilder.spawn_road_connector(this.message.patch_a, this.message.patch_b);
    this.message = null;
    return this._set_state('get_message');
  };

  return NodeInterconnectivityPlanner;

})(Planner);

RoadPlanner = (function() {
  function RoadPlanner() {}

  RoadPlanner.prototype.init = function() {
    this.msg_reader = MessageBoard.get_board('possible_node');
    return this._set_initial_state('get_message');
  };

  RoadPlanner.prototype.s_get_message = function() {
    this.message = this.msg_reader.get_message();
    if (this.message != null) {
      return this._set_state('send_road_extender');
    }
  };

  RoadPlanner.prototype.s_send_road_extender = function() {
    if (this.message == null) {
      this._set_state('get_message');
      return;
    }
    RoadBuilder.spawn_road_extender(this.message.patch);
    this.message = null;
    return this._set_state('get_message');
  };

  return RoadPlanner;

})();

PlotPlanner = (function() {
  function PlotPlanner() {}

  PlotPlanner.prototype.init = function() {
    this.boards = {
      possible: MessageBoard.get_board('possible_plot'),
      inspect: MessageBoard.get_board('inspect_plot')
    };
    return this._set_initial_state('get_message');
  };

  PlotPlanner.prototype.s_get_message = function() {
    this.message = this.boards.possible.get_message();
    if (this.message != null) {
      return this._set_state('send_plot_inspector');
    }
  };

  PlotPlanner.prototype.s_send_plot_inspector = function() {
    if (this.message == null) {
      this._set_state('get_message');
      return;
    }
    this.boards.inspect.post_message({
      patch: this.message.patch
    });
    this.message = null;
    return this._set_state('get_message');
  };

  return PlotPlanner;

})();

PlotKeeperPlanner = (function() {
  function PlotKeeperPlanner() {}

  PlotKeeperPlanner.available_plots = [];

  PlotKeeperPlanner.prototype.init = function() {
    this.board = MessageBoard.get_board('plot_built');
    return this._set_initial_state('get_message');
  };

  PlotKeeperPlanner.prototype.s_get_message = function() {
    this.message = this.board.get_message();
    if (this.message != null) {
      return PlotKeeperPlanner.available_plots.push(this.message.plot);
    }
  };

  return PlotKeeperPlanner;

})();

HousingPlanner = (function() {
  function HousingPlanner() {}

  HousingPlanner.prototype.init = function() {
    this.board = MessageBoard.get_board('new_citizen');
    return this._set_initial_state('get_message');
  };

  HousingPlanner.prototype.s_get_message = function() {
    this.message = this.board.get_message();
    if (this.message != null) {
      return this._set_state('send_house_builder');
    }
  };

  HousingPlanner.prototype.s_send_house_builder = function() {
    var block, plot;
    if (PlotKeeperPlanner.available_plots.length > 0) {
      plot = this._random_choice(PlotKeeperPlanner.available_plots);
      block = plot.get_available_block();
      if (block != null) {
        HouseBuilder.spawn_house_builder(block);
        return this._set_state('get_message');
      }
    }
  };

  HousingPlanner.prototype._random_choice = function(list) {
    return list[ABM.util.randomInt(list.length)];
  };

  return HousingPlanner;

})();

GrowthPlanner = (function() {
  function GrowthPlanner() {}

  GrowthPlanner.prototype.ticks_per_citizen = 30;

  GrowthPlanner.prototype.init = function() {
    this.msg_reader = MessageBoard.get_board('new_citizen');
    this.ticks_since_last_citizen = 0;
    return this._set_initial_state('wait_until_ready');
  };

  GrowthPlanner.prototype.s_wait_until_ready = function() {
    this.ticks_since_last_citizen += 1;
    if (this.ticks_since_last_citizen >= this.ticks_per_citizen) {
      return this._set_state('grow_population');
    }
  };

  GrowthPlanner.prototype.s_grow_population = function() {
    this.msg_reader.post_message();
    this.ticks_since_last_citizen = 0;
    return this._set_state('wait_until_ready');
  };

  return GrowthPlanner;

})();

CityModel.register_module(Planner, ['planners'], []);
