// Generated by CoffeeScript 1.7.1
var Planner, Planner_instance_properties;

Planner = (function() {
  function Planner() {}

  Planner.planners = null;

  Planner.initialize_module = function(planners_breed) {
    this.planners = planners_breed;
    return this.planners.setDefault('hidden', true);
  };

  Planner.spawn_planner = function() {
    var planner;
    planner = this.planners.create(1)[0];
    extend(planner, Planner_instance_properties);
    planner.init();
    return planner;
  };

  return Planner;

})();

Planner_instance_properties = {
  init: function() {
    return this.msg_reader = MessageBoard.get_reader('connect_nodes');
  },
  step: function() {
    var msg;
    msg = this.msg_reader.get_message();
    if (msg != null) {
      return RoadMaker.spawn_road_maker(msg.node_a.p);
    }
  }
};
