// Generated by CoffeeScript 1.7.1
var Block, House, Plot;

Plot = (function() {
  Plot.plots = null;

  Plot.initialize = function() {
    return this.plots = [];
  };

  Plot.make_plot = function(patches) {
    var plot;
    if ((patches != null) && patches.length > 0) {
      plot = new Plot(patches);
      this.plots.push(plot);
      return plot;
    }
  };

  Plot.is_part_of_plot = function(patch) {
    return (patch != null ? patch.plot : void 0) != null;
  };

  Plot.get_random_plot = function() {
    var plot, random_number, total_free_space, _i, _j, _len, _len1, _ref, _ref1;
    if (this.plots.length === 0) {
      return null;
    }
    total_free_space = 0;
    _ref = this.plots;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      plot = _ref[_i];
      if (plot.is_available()) {
        total_free_space += plot.free_space();
      }
    }
    random_number = ABM.util.randomInt(total_free_space);
    _ref1 = this.plots;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      plot = _ref1[_j];
      if (plot.is_available()) {
        random_number -= plot.free_space();
        if (random_number <= 0) {
          return plot;
        }
      }
    }
    return null;
  };

  Plot.destroy_plot = function(plot) {
    ABM.util.removeItem(this.plots, plot);
    return plot._unset_patch_references();
  };

  Plot.get_available_block = function() {
    var _ref;
    return (_ref = this.get_random_plot()) != null ? _ref.get_available_block() : void 0;
  };

  Plot.prototype.patches = null;

  Plot.prototype.blocks = null;

  Plot.prototype.under_construction = null;

  Plot.prototype.space = 0;

  function Plot(patches) {
    var p, _i, _len, _ref;
    this.patches = patches;
    this.blocks = [];
    this.under_construction = false;
    this.space = this.patches.length * 10;
    _ref = this.patches;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      p = _ref[_i];
      if (!House.is_house(p)) {
        p.color = ABM.util.randomGray(140, 170);
      }
    }
    this._set_patch_references();
  }

  Plot.prototype._set_patch_references = function() {
    var patch, _i, _len, _ref, _results;
    _ref = this.patches;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      patch = _ref[_i];
      _results.push(patch.plot = this);
    }
    return _results;
  };

  Plot.prototype._unset_patch_references = function() {
    var patch, _i, _len, _ref, _results;
    _ref = this.patches;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      patch = _ref[_i];
      _results.push(patch.plot = null);
    }
    return _results;
  };

  Plot.prototype.get_available_block = function() {
    var i, _i, _j, _len, _ref, _ref1, _results;
    _ref1 = ABM.util.shuffle((function() {
      _results = [];
      for (var _j = 0, _ref = this.patches.length - 1; 0 <= _ref ? _j <= _ref : _j >= _ref; 0 <= _ref ? _j++ : _j--){ _results.push(_j); }
      return _results;
    }).apply(this));
    for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
      i = _ref1[_i];
      if (!House.is_house(this.patches[i]) || this.patches[i].has_free_space()) {
        return this.patches[i];
      }
    }
    return null;
  };

  Plot.prototype.has_free_space = function() {
    return this.get_available_block() != null;
  };

  Plot.prototype.free_space = function() {
    return this.space - this.citizens();
  };

  Plot.prototype.get_closes_patch_to = function(patch) {
    var dist, min_dist, min_patch, p, _i, _len, _ref;
    min_dist = null;
    min_patch = null;
    _ref = this.patches;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      p = _ref[_i];
      dist = ABM.util.distance(p.x, p.y, patch.x, patch.y);
      if ((min_dist == null) || dist < min_dist) {
        min_dist = dist;
        min_patch = p;
      }
    }
    return min_patch;
  };

  Plot.prototype.is_available = function() {
    return !this.under_construction;
  };

  Plot.prototype.citizens = function() {
    var block, sum, _i, _len, _ref;
    sum = 0;
    _ref = this.blocks;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      block = _ref[_i];
      sum += block.citizens();
    }
    return sum;
  };

  return Plot;

})();

CityModel.register_module(Plot, [], []);

Block = (function() {
  Block.prototype.houses = null;

  Block.prototype.plot = null;

  Block.prototype.space = 0;

  function Block(house) {
    this.houses = [house];
    this.plot = house.plot;
    this.space = house.space;
  }

  Block.prototype.citizens = function() {
    var house, sum, _i, _len, _ref;
    sum = 0;
    _ref = this.houses;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      house = _ref[_i];
      sum += house.citizens;
    }
    return sum;
  };

  return Block;

})();

House = (function() {
  function House() {}

  House.houses = null;

  House.default_color = [100, 0, 0];

  House.max_citizens = 10;

  House.minimum_housing_available = 0.5;

  House.total_citizens = 0;

  House.initialize = function(houses) {
    this.houses = houses;
    return this.houses.setDefault('color', this.default_color);
  };

  House.make_here = function(patch) {
    this.houses.setBreed(patch);
    extend(patch, House);
    return patch.init();
  };

  House.is_house = function(patch) {
    return patch.breed === this.houses;
  };

  House.houses_below_minimum = function() {
    var free_space, house, total_space, _i, _len, _ref;
    free_space = 0;
    total_space = 0;
    _ref = this.houses;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      house = _ref[_i];
      total_space += house.space;
      free_space += house.free_space();
    }
    return (free_space / total_space) < House.minimum_housing_available;
  };

  House._update_navigation = function(house) {};

  House.prototype.block = null;

  House.prototype.citizens = 0;

  House.prototype.space = 0;

  House.prototype.init = function() {
    this.block = new Block(this);
    House._update_navigation(this);
    this.citizens = 0;
    this.space = House.max_citizens;
    this.inspector = Inspector.spawn_house_inspector(this);
    this.board = MessageBoard.get_board('new_citizen');
    return this.hospital_distance = 1;
  };

  House.prototype.has_free_space = function() {
    return this.citizens < this.space;
  };

  House.prototype.free_space = function() {
    return this.space - this.citizens;
  };

  House.prototype.increase_citizens = function() {
    if (this.has_free_space()) {
      this.citizens += 1;
      House.total_citizens += 1;
      return this.color = ABM.util.scaleColor(this.color, 1.05);
    }
  };

  House.prototype.reallocate_citizens = function() {
    var i, _i, _ref;
    for (i = _i = 0, _ref = this.citizens; 0 <= _ref ? _i <= _ref : _i >= _ref; i = 0 <= _ref ? ++_i : --_i) {
      HouseBuilder.spawn_house_builder(this, Plot.get_available_block());
    }
    return this.inspector.die();
  };

  return House;

})();

CityModel.register_module(House, [], ['houses']);
