// Generated by CoffeeScript 1.7.1
var Block, House, Plot;

Plot = (function() {
  function Plot() {}

  return Plot;

})();

Block = (function() {
  Block.prototype.patches = [];

  function Block(patch) {
    this.patches.push(patch);
  }

  return Block;

})();

House = (function() {
  function House() {}

  House.houses = null;

  House.default_color = [100, 0, 0];

  House.initialize_module = function(houses) {
    this.houses = houses;
    return this.houses.setDefault('color', this.default_color);
  };

  House.make_here = function(patch) {
    this.houses.setBreed(patch);
    extend(patch, House);
    return patch.init();
  };

  House.is_house = function(patch) {
    return patch.breed === this.houses;
  };

  House.prototype.block = null;

  House.prototype.init = function() {
    this.block = new Block(this);
    return CityModel.instance.terrainAStar.setWalkable(this, false);
  };

  return House;

})();
