// Generated by CoffeeScript 1.7.0
var CityModel, u,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

u = ABM.util;

CityModel = (function(_super) {
  __extends(CityModel, _super);

  function CityModel() {
    return CityModel.__super__.constructor.apply(this, arguments);
  }

  CityModel.prototype.setup = function() {
    var p, patch, road_maker, _i, _j, _len, _len1, _ref, _ref1;
    this.patchBreeds("city_hall roads");
    this.agentBreeds("roadMakers");
    this.anim.setRate(30, false);
    this.roads.setDefault("color", [0, 0, 255]);
    this.links.setDefault("labelColor", [255, 0, 0]);
    _ref = this.patches;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      p = _ref[_i];
      p.color = u.randomGray(120, 220);
    }
    this.city_hall = this.createCityHall(0, 0);
    _ref1 = this.city_hall.p.n;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      patch = _ref1[_j];
      Road.makeHere(patch);
    }
    patch = u.oneOf(this.city_hall.p.n4);
    road_maker = RoadMaker.makeNew(patch.x, patch.y);
    return this.links.create(this.city_hall, road_maker);
  };

  CityModel.prototype.step = function() {
    var road_maker, _i, _len, _ref, _results;
    if (this.anim.ticks % 100 === 0) {
      console.log(this.anim.toString());
    }
    _ref = this.roadMakers;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      road_maker = _ref[_i];
      _results.push(road_maker.step());
    }
    return _results;
  };

  CityModel.prototype.createCityHall = function(x, y) {
    var agent;
    agent = (this.agents.create(1))[0];
    agent.setXY(x, y);
    agent.color = [255, 0, 0];
    agent.shape = "square";
    agent.size = 1;
    return agent;
  };

  return CityModel;

})(ABM.Model);
