// Generated by CoffeeScript 1.7.1
var RoadMaker,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RoadMaker = (function(_super) {
  __extends(RoadMaker, _super);

  function RoadMaker() {
    return RoadMaker.__super__.constructor.apply(this, arguments);
  }

  RoadMaker.breed_name = 'inspectors';

  RoadMaker.breed = null;

  RoadMaker.color = [255, 255, 0];

  RoadMaker.size = 1;

  RoadMaker.radius_increment = 10;

  RoadMaker.prototype.target_point = null;

  RoadMaker.prototype.local_point = null;

  RoadMaker.prototype.ring_radius = 10;

  RoadMaker.agentSet = function() {
    var breed, _i, _len, _ref;
    if (this.breed == null) {
      _ref = ABM.agents.breeds;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        breed = _ref[_i];
        if (breed.name === this.breed_name) {
          this.breed = breed;
          break;
        }
      }
    }
    return this.breed;
  };

  RoadMaker.makeNew = function(x, y) {
    var road_maker;
    road_maker = new RoadMaker(x, y, [0, 255, 0], 1);
    this.agentSet().add(road_maker);
    return road_maker;
  };

  return RoadMaker;

})(ABM.Agent);
