// Generated by CoffeeScript 1.7.0
var RoadMaker,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RoadMaker = (function(_super) {
  __extends(RoadMaker, _super);

  RoadMaker.breed_name = 'roadMakers';

  RoadMaker.breed = null;

  RoadMaker.color = [0, 255, 0];

  RoadMaker.size = 1;

  RoadMaker.point_radius = 10;

  RoadMaker.agentSet = function() {
    var breed, _i, _len, _ref;
    if (this.breed == null) {
      _ref = ABM.agents.breeds;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        breed = _ref[_i];
        if (breed.name === this.breed_name) {
          this.breed = breed;
          break;
        }
      }
    }
    return this.breed;
  };

  RoadMaker.makeNew = function(x, y) {
    var road_maker;
    road_maker = new RoadMaker(x, y, [0, 255, 0], 1);
    this.agentSet().add(road_maker);
    return road_maker;
  };

  function RoadMaker(x, y, color, size) {
    this.color = color;
    this.size = size;
    RoadMaker.__super__.constructor.apply(this, arguments);
    this.setXY(x, y);
    this.target_point = null;
  }

  RoadMaker.prototype.step = function() {
    if (this.target_point != null) {
      if (!this.isInTarget()) {
        this.facePoint(this.target_point);
        this.forward(0.1);
        if (!Road.isRoadHere(this.p)) {
          return this.dropRoad();
        }
      } else {
        return this.target_point = this.getTargetPoint();
      }
    } else {
      return this.target_point = this.getTargetPoint();
    }
  };

  RoadMaker.prototype.dropRoad = function() {
    return Road.makeHere(this.p);
  };

  RoadMaker.prototype.isInTarget = function() {
    return 0.1 > ABM.util.distance(this.x, this.y, this.target_point.x, this.target_point.y);
  };

  RoadMaker.prototype.getTargetPoint = function() {
    var angle, radius, x, y;
    radius = ABM.util.randomFloat(this.constructor.point_radius);
    angle = ABM.util.randomFloat(360);
    x = this.x + radius * Math.cos(angle);
    y = this.y + radius * Math.sin(angle);
    return {
      x: x,
      y: y
    };
  };

  RoadMaker.prototype.facePoint = function(point) {
    var dx, dy, heading, turn;
    dx = point.x - this.x;
    dy = point.y - this.y;
    heading = Math.atan2(dy, dx);
    turn = ABM.util.subtractRads(heading, this.heading);
    return this.rotate(turn);
  };

  return RoadMaker;

})(ABM.Agent);
