// Generated by CoffeeScript 1.7.0
var Road;

Road = (function() {
  function Road() {}

  Road.breed_name = 'roads';

  Road.breed = null;

  Road.patchSet = function() {
    var breed, _i, _len, _ref;
    if (this.breed == null) {
      _ref = ABM.patches.breeds;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        breed = _ref[_i];
        if (breed.name === this.breed_name) {
          this.breed = breed;
          break;
        }
      }
    }
    return this.breed;
  };

  Road.makeHere = function(patch) {
    return this.patchSet().setBreed(patch);
  };

  Road.isRoadHere = function(patch) {
    return patch.breed === this.patchSet();
  };

  return Road;

})();
