// Generated by CoffeeScript 1.7.0
var Road, RoadMaker,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Road = (function() {
  function Road() {}

  Road.breed_name = 'roads';

  Road.breed = null;

  Road.patchSet = function() {
    var breed, _i, _len, _ref;
    if (this.breed == null) {
      _ref = ABM.patches.breeds;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        breed = _ref[_i];
        if (breed.name === this.breed_name) {
          this.breed = breed;
          break;
        }
      }
    }
    return this.breed;
  };

  Road.makeHere = function(patch) {
    return this.patchSet().setBreed(patch);
  };

  Road.isRoadHere = function(patch) {
    return patch.breed === this.patchSet();
  };

  return Road;

})();

RoadMaker = (function(_super) {
  __extends(RoadMaker, _super);

  RoadMaker.breed_name = 'roadMakers';

  RoadMaker.breed = null;

  RoadMaker.color = [0, 255, 0];

  RoadMaker.size = 1;

  RoadMaker.agentSet = function() {
    var breed, _i, _len, _ref;
    if (this.breed == null) {
      _ref = ABM.agents.breeds;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        breed = _ref[_i];
        if (breed.name === this.breed_name) {
          this.breed = breed;
          break;
        }
      }
    }
    return this.breed;
  };

  RoadMaker.makeNew = function(x, y) {
    var road_maker;
    road_maker = new RoadMaker(x, y, [0, 255, 0], 1);
    this.agentSet().add(road_maker);
    return road_maker;
  };

  function RoadMaker(x, y, color, size) {
    this.color = color;
    this.size = size;
    RoadMaker.__super__.constructor.apply(this, arguments);
    this.setXY(x, y);
    this.target_point = null;
  }

  RoadMaker.prototype.step = function() {
    this.forward(0.1);
    if (!Road.isRoadHere(this.p)) {
      return this.dropRoad();
    }
  };

  RoadMaker.prototype.dropRoad = function() {
    return Road.makeHere(this.p);
  };

  return RoadMaker;

})(ABM.Agent);
