// Generated by CoffeeScript 1.7.1
var Road;

Road = (function() {
  function Road() {}

  Road.breed_name = 'roads';

  Road.breed = null;

  Road.connectivity_threshold = 0.2;

  Road.patchSet = function() {
    var breed, _i, _len, _ref;
    if (this.breed == null) {
      _ref = ABM.patches.breeds;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        breed = _ref[_i];
        if (breed.name === this.breed_name) {
          this.breed = breed;
          break;
        }
      }
    }
    return this.breed;
  };

  Road.makeHere = function(patch) {
    var n_patch, _i, _len, _ref;
    this.patchSet().setBreed(patch);
    CityModel.instance.roadAStar.setWalkable(patch);
    patch.color = [0, 100, 0];
    patch.connectivity = 1.0;
    _ref = patch.n;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      n_patch = _ref[_i];
      if (n_patch.connectivity < patch.connectivity) {
        this.setConnectivity(n_patch, 1.0);
      }
    }
    return null;
  };

  Road.setConnectivity = function(patch, connectivity) {
    patch.connectivity = connectivity;
    if (connectivity === 1) {
      patch.connectivity_color = [30, 130, 30];
    } else if (connectivity === 0.5) {
      patch.connectivity_color = [60, 160, 60];
    } else if (connectivity === 0.25) {
      patch.connectivity_color = [90, 190, 90];
    }
    return this.spreadConnectivity(patch);
  };

  Road.spreadConnectivity = function(patch) {
    var n_patch, new_connectivity, _i, _len, _ref;
    new_connectivity = patch.connectivity / 2;
    if (new_connectivity > this.connectivity_threshold) {
      _ref = patch.n;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        n_patch = _ref[_i];
        if (n_patch.connectivity < patch.connectivity) {
          this.setConnectivity(n_patch, new_connectivity);
        }
      }
    }
    return null;
  };

  Road.isRoadHere = function(patch) {
    return patch.breed === this.patchSet();
  };

  return Road;

})();
