// Generated by CoffeeScript 1.7.1
var __slice = [].slice;

(function($, window) {
  var CitySimulation;
  CitySimulation = (function() {
    CitySimulation.prototype.defaults = {
      paramA: 'foo',
      paramB: 'bar'
    };

    function CitySimulation(el, options) {
      this.options = $.extend({}, this.defaults, options);
      this.$el = $(el);
      this.setup_hotkeys();
      this.setup_model();
    }

    CitySimulation.prototype.setup_model = function() {
      this.model = new CityModel(this.$el.attr('id'), 16, -16, 16, -16, 16);
      this.seed = GPW.pronounceable(8);
      return this.seed = "ousphoun";
    };

    CitySimulation.prototype.run = function() {
      Math.seedrandom(this.seed);
      this.model.debug();
      return this.model.start();
    };

    CitySimulation.prototype.restart = function() {
      this.model.reset();
      this.setup_model();
      return this.run();
    };

    CitySimulation.prototype.set_key_command = function(key, fn) {
      return $(document).bind('keydown', key, fn);
    };

    CitySimulation.prototype.setup_hotkeys = function() {
      this.set_key_command('a', function() {
        return console.log('A');
      });
      return this.set_key_command('alt+r', (function(_this) {
        return function() {
          return _this.restart();
        };
      })(this));
    };

    CitySimulation.prototype.get_model = function() {
      return this.model;
    };

    return CitySimulation;

  })();
  return $.fn.extend({
    CitySimulation: function() {
      var args, option, ret_val;
      option = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
      ret_val = null;
      this.each(function() {
        var $this, data;
        $this = $(this);
        data = $this.data('CitySimulation');
        if (!data) {
          ret_val = $this.data('CitySimulation', (data = new CitySimulation(this, option)));
        }
        if (typeof option === 'string') {
          return ret_val = data[option].apply(data, args);
        }
      });
      if (ret_val != null) {
        return ret_val;
      } else {
        return $(this);
      }
    }
  });
})(window.jQuery, window);
