// Generated by CoffeeScript 1.7.1
var App;

App = (function() {
  function App() {}

  App.prototype.pause = false;

  App.prototype.setup = function(element) {
    this.element = element;
    this.setup_hotkeys();
    this.setup_model();
    return this.setup_buttons();
  };

  App.prototype.setup_model = function() {
    this.model = new CityModel(this.element.attr('id'), 16, -16, 16, -16, 16);
    this.seed = GPW.pronounceable(8);
    return this.seed = "therinet";
  };

  App.prototype.run = function() {
    Math.seedrandom(this.seed);
    return this.model.reset(true);
  };

  App.prototype.restart = function() {
    Math.seedrandom(this.seed);
    return this.model.reset(true);
  };

  App.prototype.play_pause_model = function() {
    if (this.paused) {
      this.model.start();
      $('#step').attr('disabled', true);
    } else {
      this.model.stop();
      $('#step').attr('disabled', false);
    }
    this.paused = !this.paused;
    return null;
  };

  App.prototype.step_model = function() {
    if (this.paused) {
      this.model.anim.step();
      return this.model.anim.draw();
    }
  };

  App.prototype.set_key_command = function(key, fn) {
    return $(document).bind('keydown', key, fn);
  };

  App.prototype.setup_hotkeys = function() {
    return this.set_key_command('r', (function(_this) {
      return function() {
        return _this.restart();
      };
    })(this));
  };

  App.prototype.setup_buttons = function() {
    $('#play-pause').click((function(_this) {
      return function() {
        _this.play_pause_model();
        return $('#play-pause span').toggleClass('glyphicon-play').toggleClass('glyphicon-pause');
      };
    })(this));
    $('#step').click((function(_this) {
      return function() {
        return _this.step_model();
      };
    })(this));
    $('#reload').click((function(_this) {
      return function() {
        return _this.restart();
      };
    })(this));
    $('button.j-iterate-over').click((function(_this) {
      return function() {
        return _this.animate(parseInt($('input.j-iterate-over').val()));
      };
    })(this));
    return $('button.j-iterate-until').click((function(_this) {
      return function() {
        return _this.animateTo(parseInt($('input.j-iterate-until').val()));
      };
    })(this));
  };

  App.prototype.get_model = function() {
    return this.model;
  };

  App.prototype.animate = function(ticks) {
    var i;
    this.model.stop();
    i = 0;
    while (i < ticks) {
      this.model.anim.step();
      i += 1;
    }
    return this.model.start();
  };

  App.prototype.animateTo = function(ticks) {
    this.model.stop();
    while (this.model.anim.ticks < ticks) {
      this.model.anim.step();
    }
    return this.model.start();
  };

  return App;

})();
