// Generated by CoffeeScript 1.7.1
require.config({
  paths: {
    'jquery': 'vendor/jquery-2.1.0',
    'GPW': 'vendor/gpw'
  },
  shim: {
    'jquery': {
      exports: '$'
    },
    'GPW': {
      exports: 'GPW'
    }
  }
});

require(['jquery', 'GPW', 'vendor/seedrandom', 'city/CityModel'], function($, GPW, seedrandom, CityModel) {
  var model, seed;
  console.log("Loaded main.coffee");
  model = new CityModel('layers', 16, -16, 16, -16, 16);
  seed = GPW.pronounceable(8);
  Math.seedrandom(seed);
  model.debug();
  return model.start();
});
