// Generated by CoffeeScript 1.7.0
var MyModel, model, u,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

u = ABM.util;

MyModel = (function(_super) {
  __extends(MyModel, _super);

  function MyModel() {
    return MyModel.__super__.constructor.apply(this, arguments);
  }

  MyModel.prototype.setup = function() {
    var patch, tree, _i, _j, _len, _ref, _ref1, _results;
    this.agentBreeds("embers fires");
    this.patchBreeds("trees");
    this.agents.setDefault("shape", "square");
    this.agents.setDefault("heading", 0);
    this.fires.setDefault("color", [255, 0, 0]);
    this.ember_default_color = [255, 34, 34];
    this.embers.setDefault("color", this.ember_default_color);
    this.embers.setDefault("intensity", 1);
    this.trees.setDefault("color", [0, 255, 0]);
    this.trees.setDefault("burnt", false);
    this.refreshPatches = false;
    this.anim.setRate(60, false);
    this.density = 65;
    this.ember_decay_rate = 0.3;
    this.spread_time = 0;
    this.cooloff_time = 0;
    this.iters = 0;
    this.n_fires = 0;
    this.n_embers = 0;
    _ref = this.patches;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      patch = _ref[_i];
      if (u.randomInt(100) < this.density) {
        this.trees.setBreed(patch);
      }
    }
    _ref1 = this.trees;
    _results = [];
    for (_j = _ref1.length - 1; _j >= 0; _j += -1) {
      tree = _ref1[_j];
      if (tree.x === this.patches.minX) {
        _results.push(this.ignite(tree));
      }
    }
    return _results;
  };

  MyModel.prototype.ignite = function(tree) {
    tree.sprout(1, this.fires);
    tree.burnt = true;
    tree.color = [0, 0, 0];
    return tree.draw(this.contexts.patches);
  };

  MyModel.prototype.spread = function(fire) {
    var tree, _i, _len, _ref;
    _ref = fire.p.n4;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tree = _ref[_i];
      if (tree.breed.name === "trees" && !tree.burnt) {
        this.ignite(tree);
      }
    }
    fire.p.sprout(1, this.embers);
    return fire.die();
  };

  MyModel.prototype.coolOff = function(ember) {
    ember.intensity *= 1 - this.ember_decay_rate;
    ember.color = u.scaleColor(this.ember_default_color, ember.intensity);
    if (ember.intensity < .5) {
      return ember.die();
    }
  };

  MyModel.prototype.step = function() {
    var ember, fire, iter_end, iter_start, _i, _j, _ref, _ref1;
    if (!this.agents.any()) {
      console.log("..stopping, fire done at tick: " + this.anim.ticks);
      this.stop();
    }
    this.n_embers += this.embers.length;
    iter_start = performance.now();
    _ref = this.embers;
    for (_i = _ref.length - 1; _i >= 0; _i += -1) {
      ember = _ref[_i];
      this.coolOff(ember);
    }
    iter_end = performance.now();
    this.cooloff_time += iter_end - iter_start;
    this.n_fires += this.fires.length;
    iter_start = performance.now();
    _ref1 = this.fires;
    for (_j = _ref1.length - 1; _j >= 0; _j += -1) {
      fire = _ref1[_j];
      this.spread(fire);
    }
    iter_end = performance.now();
    this.spread_time += iter_end - iter_start;
    this.iters++;
    if (this.anim.ticks % 10 === 0) {
      console.log(this.anim.toString());
      this.spread_time = 0;
      this.cooloff_time = 0;
      this.iters = 0;
      this.n_fires = 0;
      return this.n_embers = 0;
    }
  };

  return MyModel;

})(ABM.Model);

model = new MyModel("layers", 2, -125, 125, -125, 125);

model.debug();

model.start();
